[package]
name = "barebones-x509"
version = "0.5.2"
authors = ["Parity Technologies <admin@parity.io>", "Demi Marie Obenour <demiobenour@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Low-level X.509 parsing and signature verification library"
repository = "https://github.com/DemiMarie/barebones-x509"
keywords = ["X509", "ASN1", "cryptography", "pki"]
readme = "README.md"

[dependencies]
ring = { version = "0.17.7", default-features = false }
untrusted = "0.9.0"
w = { package = "webpki", version = "0.22.4", optional = true, default-features = false }
r = { package = "rustls", version = "0.22.2", optional = true }

[dev-dependencies]
chrono = "0.4.33"

[features]
default = ["rsa"]
rsa = ["ring/alloc"]
webpki = ["w"]
rustls = ["r", "std"]
std = ["w/std"]
legacy-certificates = []
obsolete-unique-ids = ["legacy-certificates"]

[package.metadata.docs.rs]
rustc-args = ["--cfg", "docsrs"]
