edition = "2021"
fn_params_layout = "Compressed"
fn_single_line = true
match_arm_blocks = false
match_block_trailing_comma = true
max_width = 100
imports_granularity = "Crate"
newline_style = "Unix"
reorder_imports = true
trailing_comma = "Vertical"
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
